### ISSUE TITLE
Accidently installed docker snap while having docker dpkg installed.

### ISSUE THREAD

**Issue by thomas15v** [docker/docker-snap#12]
Hi, I am having a rather annoying issue, while I was messing around in a VM I apparently disconnected through SSH. I happily did `sudo snap install docker`  on my host machine that was running a few development containers. After noticing my mistake I uninstalled the snap package, but it was already too late. 

I attempted to remove and reinstall my normal docker install but that didn't helped. Basicly docker can not remove/stop/kill/start containers because permissions issues.

Starting
```
ERROR: for db  Cannot start service db: mkdir /var/run/docker/libcontainerd/containerd/15cb2e0b612ac94ea3a48a16f94c045dbeb02a90867d106169022459b8576674: file exists
```
Stopping a new container
```
Cannot stop container e51a26232f662a497c2523224f811d78ab9b5786d1acff27271a32ea4f6cff59: Cannot kill container e51a26232f662a497c2523224f811d78ab9b5786d1acff27271a32ea4f6cff59: rpc error: code = 7 desc = permission denied
```

It wouldn't be that bad if I could get 1 container running to get the prepared data of a postgresql container.

As for the issue. It would be nice if the snap package fails to install if an older docker installation has been installed.

Thank you

**Comment by thomas15v** [comment]
I solved my issue, the snap docker actually was already running some of my containers, but upon removing the snap package it didn't correctly shut those down. Creating zombie processes of `docker-containerd-shim`. I don't know if it is worth looking into this tho. Restarting the server cleaned those up and I was abbe to restart my containers.

**Comment by psftw** [comment]
Thanks for the feedback.  The snap and non-snap versions don't get along well, so we don't support upgrading from one to the other (discussed previously -
 https://github.com/docker/docker-snap/issues/4).  In general since they store data in different places, most of the problems are related to apparmor profiles, which a reboot can help with.  I don't think it makes sense to try to have the snap detect this scenario.  I'll keep an eye out for the zombie issue.  Closing, but feel free to continue the conversation. :+1:
