### ISSUE TITLE
No command completion for docker snap

### ISSUE THREAD

**Issue by ghost** [docker/docker-snap#24]
Maybe there is a way to add command completion for the docker snap? In the actual stable channel i can't see a way to enable it. Thanks for your effort.

**Comment by cardonator** [comment]
You have to install the bash completions package for docker. This isn't done automatically for snap.

**Comment by RockOnHero** [comment]
@cardonator Thank you for the advise. I am not sure, but shouldn't it be possible to get the bash-completion with the snap? With the docker PPA it is and Snapcraft has the option to include bash-completion since version 2.33. If this article is correct: http://news.softpedia.com/news/canonical-outs-snapcraft-2-33-snap-tool-for-ubuntu-with-bash-completion-support-517392.shtml

**Comment by jehos** [comment]
here, just dirty script for update bash completion.
put on `/etc/bash_completion.d/docker`

https://gist.github.com/jehos/87d0d2ec08c026af4e7b39d6d607ed6f

**Comment by anonymouse64** [comment]
Hi folks, I added bash completion for the docker snap in the edge channel. You can try it out by refreshing to the edge channel with:

```
sudo snap refresh docker --edge
```
The changes in the edge channel should show up in stable in a short while if you don't wish to use edge.

**Comment by psftw** [comment]
Closing all issues and pull requests since this repo is getting archived (see notice at the top of README).
