### ISSUE TITLE
[Errno 13] Permission denied: u'./docker-compose.yml

### ISSUE THREAD

**Issue by marcossegovia** [docker/docker-snap#26]
Hi there,
I followed the guide step by step on using docker for the first time on ubuntu core 16
But I came across with this message every time i try to run the containers from the yml
```
docker.compose up
```
It gives me `ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.`

While
```
sudo docker.compose up
```
It gives me `ERROR: .IOError: [Errno 13] Permission denied: u'./docker-compose.yml'`

**Comment by marcossegovia** [comment]
The whole repository even the docker-compose.yml file is set to my user:user. Moreover the docker-compose.yml has 777 permission

**Comment by adglkh** [comment]
Hi @marcossegovia 
Thanks for your report, you hit the AppArmor denials due to the strict confinement in the snappy world. 
In short, you need to
1. make home plug connected if you put the whole repository under $HOME 
2. make sure the whole repository(docker project folder and files) owned by **root** instead of your login user i.e Dockerfile, docker-compose.yml. 

Here is how I build an image with docker build command in ubuntu core. It applies to docker compose command too.
https://paste.ubuntu.com/25814535/
For more details, please refer to 
https://forum.snapcraft.io/t/docker-load-fails-with-permission-denied/1227

Please let us know if it works for you with the above approach. 
Thanks for your interests in docker snap.

BR
Gary

**Comment by marcossegovia** [comment]
Hey @adglkh 
Thank you for your quickly and accurate response.
I think that `sudo chown root.root -R` on the whole repository made the deal. Although having executed `sudo chown root:root -R` previously.

Now I got problems pulling the images

```
`$ sudo docker.compose up`
Pulling db (mongo:latest)...
latest: Pulling from library/mongo
ERROR: no matching manifest for linux/arm in the manifest list entries
```

If you have any idea would be nice, otherwise I think we can close this. :)

**Comment by marcossegovia** [comment]
Well actually I'm seeing docker has a restricted number of images: https://hub.docker.com/u/arm64v8/ on the raspberry architecture :(
