### ISSUE TITLE
error while creating mount source path

### ISSUE THREAD

**Issue by janmyszkier** [docker/docker-snap#31]
The issue has been previously submitted here:
https://github.com/linuxserver/docker-tautulli/issues/44
but submitter solved it by uninstalling the snap package (which doesn't solve the issue)

today I also run into the same problem using snap package. 

Works fine with docker ubuntu `artful` repo. 
Doesn't work if I use snap package.
Please look into this and make them compatible.

**Comment by GS-JS** [comment]
To add more info to anyone who runs into this issue, it's because the snap package is adhering to the default permissions/privileges that snap packages are granted. Some other snaps get around this issue by instructing users to install with the `--classic` flag passed in - but imitating the legacy permissions defeats the purpose of the security scoping done in snaps.

For reference:
docker-compose.yaml
```
version: '3'
services:
    my_service:
        volumes:
            - ~/.hidden_folder:/root/.hidden_folder
...
```

`$ docker.compose up`
`$ docker inspect container_id`
```
...
"Mounts": [
    {
        "Type": "bind",
        "Source": "/home/my_user/snap/docker/179/.hidden_folder",
        "Destination": "/root/.hidden_folder",
        "Mode": "rw",
        "RW": true,
        "Propogation": "rprivate"
    }
...
```

**Comment by cacois** [comment]
@GS-JS  so what i'm hearing is that a snap may be a bad fit for a docker deliver method?

**Comment by GS-JS** [comment]
@cacois I'm not familiar enough with Ubuntu/Docker/Snap enough to say for sure that this, or other Docker+Snap issues, is a show-stopper - apologies. Maybe Docker+Snap actually warrants the `--classic` flag to function appropriately.

**Comment by psftw** [comment]
Closing all issues and pull requests since this repo is getting archived (see notice at the top of README).
